### ISSUE TITLE
ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by silvacarl2** [remsky/Kokoro-FastAPI#53]
when running the docker, we get this error: ModuleNotFoundError: No module named 'models'

**Comment by remsky** [comment]
Is this on the most recent version? 

If not you may have to update, or if you want to keep it stable as is, you should be able to edit the docker compose to use the image of the previous tags , or set it to build from source.

[v0.0.5post1](https://github.com/remsky/Kokoro-FastAPI/releases/tag/v0.0.5post1)
[remsky/Kokoro-FastAPI/tree/v0.0.5post1-stable](https://github.com/remsky/Kokoro-FastAPI/tree/v0.0.5post1-stable)

e.g, for the previous branch compose
```yaml
kokoro-tts:
    # image: ghcr.io/remsky/kokoro-fastapi-gpu:v0.1.0
    build:
      context: .
      dockerfile: Dockerfile.cpu
```
    or
    
```yaml
kokoro-tts:
    image: ghcr.io/remsky/kokoro-fastapi-gpu:v0.0.5post1
    # build:
    #   context: ../..
    #   dockerfile: docker/gpu/Dockerfile
    volumes:
```

Let me know if it still gives you trouble, as new version should have the models baked directly into the docker image and no longer require the separate git lfs pull container step
